services:
  postgres:
    container_name: postgres
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_USER: holonet
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: holonet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  valkey:
    image: docker.io/bitnami/valkey:8.1
    environment:
      - ALLOW_EMPTY_PASSWORD=yes # Only allow empty password for DEV
      - VALKEY_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - valkey_data:/bitnami/valkey/data

#  keycloak:
#    container_name: keycloak
#    image: quay.io/keycloak/keycloak:26.1.4
#    environment:
#      KC_BOOTSTRAP_ADMIN_USERNAME: admin
#      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
#    ports:
#      - "8080:8080"
#    command: start-dev

#  droid:
#    container_name: droid
#    image: ghcr.io/r2unit/holonet-droid:1
#    environment:
#      - WS_URL=ws://holonet:8080/ws
#      - TOKEN=insecure
#      - DROID_NAME=worker01
#      - DEBUG=false

volumes:
  postgres_data:
    driver: local
  valkey_data:
    driver: local