services:
  postgres:
    container_name: postgres
    image: postgres:17-bookworm
    restart: always
    environment:
      POSTGRES_USER: holonet
      POSTGRES_PASSWORD: insecure
      POSTGRES_DB: holonet
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
    driver: local