services:

  postgres:
     container_name: postgres
     image: postgres:17-bookworm
     restart: always
     environment:
       POSTGRES_USER: talos
       POSTGRES_PASSWORD: saxofoon
       POSTGRES_DB: talos
     ports:
       - "5432:5432"
     volumes:
       - postgres_data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: docker.io/bitnami/redis:7.4
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'



  
volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local